#pragma once

// constant buffer register
#define DRAW_INFO_BIND_INDEX 0
#define MAT_BASE_BIND_INDEX 1
#define MAT_INS_BIND_INDEX 2
#define CAM_BIND_INDEX 3
#define DIRECT_LIGHT_BIND_INDEX 4
#define CB_START_BIND_INDEX 5

// input slot
#define TRANS_INDEX_BIND_INDEX 0

// texture register
#define TRANS_BIND_INDEX 0
#define PARTICLE_BIND_INDEX 1
#define PROBE_GRID_DATA_BIND_INDEX 2
#define PROBE_GRID_LIST_BIND_INDEX 3
#define PROBE_GRID_HEAD_BIND_INDEX 4
#define RELFECTION_PROBE_CUBEMAP_INDEX 5
#define RELFECTION_PROBE_CUBEMAP_SAMPLER_INDEX 0
#define TERRAIN_MAP_BIND_INDEX 6
#define TERRAIN_MAP_SAMPLER_INDEX 1
#define TEX_START_BIND_INDEX 7